Events display
uchicago-capp-30320/ShoulderToShoulder pull request #100
Opened 2024-05-12 18:16 UTC by chanteriam

## Describe your changes
Makes the past + upcoming event data accurate to the user's events and allows users to review past events.

## Checklist before merging

- [x] My code produces no errors when run
- [x] My code is linted and properly formatted

2024-05-13 15:05 UTC, sarahwalker10 requested changes
1. I recommend changing the "Did you attend this event?" to a slide "Yes" + "No" option, bc right now it is not intuitive that I need to click "No" in oder to say "yes". 
<img width="1085" alt="Screenshot 2024-05-13 at 10 04 11 AM" src="https://github.com/uchicago-capp-30320/ShoulderToShoulder/assets/111753956/f027de0c-1ba6-4184-a511-4dff032ccc98">

2. I notice that when I receive a pop-up about an event I've been invited to, after i click "Sign Me Up!", the event does not appear in my "Upcoming events" until after I refresh the page.

2024-05-14 17:52 UTC, ehabich reviewed
I just added one thing to be fixed in the documentation of the user_events.py model, but otherwise this looks great.

Nice to haves (but not necessary for this merge): 
1. removing star review highlight from Past Events that have already been reviewed
2. adding day of week to upcoming event dates

2024-05-14 17:52 UTC, ehabich commented on backend/shoulder/s2s/db_models/user_events.py
Please add 'rsvp' and 'attended' column descriptions into the docstring unless the backend team does this in a different PR

2024-05-14 18:49 UTC, chanteriam commented on backend/shoulder/s2s/db_models/user_events.py
Implemented the changes. Added a screen recording to the frontend slack channel.

2024-05-14 19:57 UTC, ehabich approved these changes
Looks incredible!

2024-05-14 19:58 UTC, merged