Update settings.py with AWS Database information
uchicago-capp-30320/ShoulderToShoulder pull request #35
Opened 2024-04-12 12:47 UTC by necabotheking

## Describe your changes

Updates settings.py to ensure that all members can connect to the AWS database

## Checklist before merging

- [X] My code produces no errors when run
- [X] My code is linted and properly formatted

2024-04-12 14:38 UTC, chanteriam commented
Since the env file keeping the database credentials is in the gitignore, can you send it to us in Slack and add instructions in this PR about where that file should go?

2024-04-12 14:41 UTC, chanteriam requested changes

2024-04-12 14:41 UTC, chanteriam commented on backend/ShoulderToShoulder/s2s/db_models/event.py
> +from django.db import models
For documentation purposes, can you add doc strings before each of the models describing what they are used to represent?

2024-04-12 14:41 UTC, chanteriam commented on backend/ShoulderToShoulder/s2s/db_models/event.py
> +    def __str__(self) -> str:
Make sure to double check that the __str__ function is correct; right now, it is trying to print the event model using `self.description`, but `self.description` doesn't exist in this model.

2024-04-12 19:26 UTC, chanteriam approved these changes

2024-04-12 23:44 UTC, chanteriam requested changes
Hi there! One more thing: since we added the environment and JWT stuff, this branch requires the installation of more packages; these installation instructions should also be added to your PR and the packages added to a requirements.txt file:
`pip install django-environment`
`pip install django-environ`
`pip install djangorestframework-simplejwt`

2024-04-13 23:22 UTC, necabotheking commented
@chanteriam We should be set now! Thanks for the corrections.

2024-04-13 23:23 UTC, chanteriam approved these changes

2024-04-13 23:27 UTC, merged