Create Backend API Endpoints
uchicago-capp-30320/ShoulderToShoulder pull request #57
Opened 2024-04-17 18:30 UTC by necabotheking

## Describe your changes
TODO
## Checklist before merging

- [ ] My code produces no errors when run
- [ ] My code is linted and properly formatted

2024-04-29 00:12 UTC, sarahwalker10 approved these changes
Thank you, Aïcha! Looks good to me

2024-04-30 13:43 UTC, sarahwalker10 submitted a review, later dismissed

2024-04-30 15:18 UTC, chanteriam requested changes

2024-04-30 15:18 UTC, chanteriam commented on backend/shoulder/ShoulderToShoulder/settings.py
> +# MEDIA_ROOT = os.path.join(settings.BASE_DIR, 'media')
Delete this commented out line

2024-04-30 15:18 UTC, chanteriam commented on backend/shoulder/s2s/db_models/availability.py
> +            calendar_id (str): primary key of calendar table if user available
add to docstrings a description of the available column

2024-04-30 15:18 UTC, chanteriam commented on backend/shoulder/s2s/db_models/choice.py
> +        age_range:
adit column description here, categories is a JSON field of potential choices

2024-04-30 15:18 UTC, chanteriam commented on backend/shoulder/s2s/db_models/event_suggestion.py
> +    moday_early_morning = models.BooleanField()
mispelling of monday

2024-04-30 15:18 UTC, chanteriam commented on backend/shoulder/s2s/db_models/event_suggestion.py
> +    duration_9hr = models.BooleanField()
since max duration is set to 8hrs, we probably don't need the 9-12 hour columns anymore

2024-04-30 15:18 UTC, chanteriam commented on backend/shoulder/s2s/db_models/event_suggestion.py
> +    # event2_id =
delete commented out fields

2024-04-30 15:18 UTC, chanteriam commented on backend/shoulder/s2s/db_models/onboarding.py
> +    Table Columns:
add the rest of the table columns to docstrings

2024-04-30 15:18 UTC, chanteriam commented on backend/shoulder/s2s/db_models/scenarios.py
> +
add the duration preference to docstrings

2024-04-30 15:18 UTC, chanteriam commented on backend/shoulder/s2s/db_models/suggestion_results.py
> +        user_id:
finish adding descriptions of columns

2024-04-30 15:18 UTC, chanteriam commented on backend/shoulder/s2s/db_models/user_events.py
> +    Includes user ranking of events attended.
add column descriptions

2024-04-30 15:18 UTC, chanteriam commented on backend/shoulder/s2s/db_models/user_events.py
> +    user_rating = models.ForeignKey(choices=ALLOWED_RATINGS)
user rating shouldn't be a ForeignKey field

2024-04-30 15:18 UTC, chanteriam commented on backend/shoulder/s2s/urls.py
> +router.register(r"eventsuggestions", views.EventSuggestionsViewSet)
Register the ML model viewset here as well

2024-05-03 19:31 UTC, chanteriam approved these changes

2024-05-03 19:46 UTC, merged