Fix availability
uchicago-capp-30320/ShoulderToShoulder pull request #93
Opened 2024-05-08 00:44 UTC by chanteriam

## Describe your changes
This PR adds day of week and time of day to the availability table and removes the calendar table. This results in faster update/creation time for user availability (from 50 to 5 seconds)

## Checklist before merging

- [x] My code produces no errors when run
- [x] My code is linted and properly formatted

2024-05-08 17:02 UTC, sarahwalker10 requested changes
**2 changes, 1 question:**

Change 1. Should the playground.py and playground2.py files be removed? They seem like testing files.

Change 2. The transition from onboarding to seeing the completed profile is still missing (it remains on this page indefinitely):

<img width="1065" alt="Screenshot 2024-05-08 at 12 26 25 PM" src="https://github.com/uchicago-capp-30320/ShoulderToShoulder/assets/111753956/807d871c-2e1f-4b60-be98-9ae1eadf9cad">



Question 1. Also quick question just bc I'm curious, why this is like this in the availability.py model (tuples with the repeated values)?:
```
DAY_CHOICES = (
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday'),
    ) 
```

2024-05-08 17:30 UTC, sarahwalker10 commented
However, can confirm that 1. creating the profile and having the info saved to the database happens in only a few seconds; and 2. updating the availability and making profile updates get changed in the database also very quickly (whereas previously it took over 1 min to update calendar availability) (P.S. nice touch adding the pop-up "Please wait while we update your availability")

2024-05-08 19:43 UTC, ehabich requested changes

2024-05-08 19:43 UTC, ehabich commented on playground.py
Agree with sarah on this file. Is it mean tot be included? It seems like yes but would you change the filename to somethign more informative if so or delete if not?

2024-05-08 19:43 UTC, ehabich commented on playground2.py
same on this file

2024-05-09 02:28 UTC, sarahwalker10 approved these changes

2024-05-09 02:43 UTC, sarahwalker10 submitted a review, later dismissed

2024-05-09 03:01 UTC, merged